//! Squared Euclidean distance as a Bregman divergence.
//!
//! D(p‖q) = ½‖p - q‖² is the unique *symmetric* Bregman divergence,
//! generated by φ(x) = ½‖x‖².

use serde::{Deserialize, Serialize};

/// Squared Euclidean divergence: D(p‖q) = ½‖p - q‖².
///
/// This is the Bregman divergence generated by φ(x) = ½‖x‖².
/// It is the **only** symmetric Bregman divergence.
///
/// # Properties
///
/// - **Symmetric**: D(p‖q) = D(q‖p)
/// - **Non-negative**: D(p‖q) ≥ 0 with equality iff p = q
/// - **Triangle inequality** for √D (i.e., Euclidean distance satisfies it)
/// - **Convex** in both arguments
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SquaredEuclidean;

impl SquaredEuclidean {
    /// Create a new squared Euclidean divergence.
    pub fn new() -> Self {
        Self
    }

    /// Compute D(p‖q) = ½‖p - q‖².
    pub fn divergence(&self, p: &[f64], q: &[f64]) -> f64 {
        assert_eq!(p.len(), q.len());
        0.5 * p
            .iter()
            .zip(q.iter())
            .map(|(pi, qi)| (pi - qi) * (pi - qi))
            .sum::<f64>()
    }

    /// Compute the Euclidean distance √(2·D(p‖q)).
    pub fn distance(&self, p: &[f64], q: &[f64]) -> f64 {
        (2.0 * self.divergence(p, q)).sqrt()
    }

    /// Verify symmetry: D(p‖q) = D(q‖p).
    pub fn verify_symmetry(&self, p: &[f64], q: &[f64]) -> bool {
        (self.divergence(p, q) - self.divergence(q, p)).abs() < 1e-10
    }
}

/// Mahalanobis distance: D_M(p‖q) = ½(p-q)ᵀ A⁻¹ (p-q).
///
/// A generalization of squared Euclidean distance using a positive-definite
/// weighting matrix A. Also a Bregman divergence with φ(x) = ½ xᵀAx.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MahalanobisDistance {
    /// Positive-definite weighting matrix A.
    pub a: Vec<Vec<f64>>,
}

impl MahalanobisDistance {
    /// Create a new Mahalanobis distance with weighting matrix A.
    pub fn new(a: Vec<Vec<f64>>) -> Self {
        Self { a }
    }

    /// Compute the Mahalanobis distance D(p‖q) = ½(p-q)ᵀ A⁻¹ (p-q).
    pub fn divergence(&self, p: &[f64], q: &[f64]) -> f64 {
        assert_eq!(p.len(), q.len());
        let n = p.len();
        let diff: Vec<f64> = p.iter().zip(q.iter()).map(|(pi, qi)| pi - qi).collect();

        // Compute A⁻¹ diff, then dot with diff
        let inv = self.invert();
        let mut result = 0.0;
        for i in 0..n {
            let mut row_sum = 0.0;
            for j in 0..n {
                row_sum += inv[i][j] * diff[j];
            }
            result += diff[i] * row_sum;
        }
        0.5 * result
    }

    /// Invert the weighting matrix using Gauss-Jordan elimination.
    #[allow(clippy::needless_range_loop)]
    fn invert(&self) -> Vec<Vec<f64>> {
        let n = self.a.len();
        let mut aug = vec![vec![0.0; 2 * n]; n];
        for i in 0..n {
            for j in 0..n {
                aug[i][j] = self.a[i][j];
            }
            aug[i][n + i] = 1.0;
        }
        for col in 0..n {
            let mut max_row = col;
            for row in col + 1..n {
                if aug[row][col].abs() > aug[max_row][col].abs() {
                    max_row = row;
                }
            }
            aug.swap(col, max_row);
            let pivot = aug[col][col];
            for j in 0..2 * n {
                aug[col][j] /= pivot;
            }
            for row in 0..n {
                if row == col {
                    continue;
                }
                let factor = aug[row][col];
                for j in 0..2 * n {
                    aug[row][j] -= factor * aug[col][j];
                }
            }
        }
        let mut inv = vec![vec![0.0; n]; n];
        for i in 0..n {
            for j in 0..n {
                inv[i][j] = aug[i][n + j];
            }
        }
        inv
    }
}

impl Default for SquaredEuclidean {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_squared_euclidean_basic() {
        let se = SquaredEuclidean::new();
        let p = vec![1.0, 2.0];
        let q = vec![4.0, 6.0];
        let d = se.divergence(&p, &q);
        // ½((1-4)² + (2-6)²) = ½(9+16) = 12.5
        assert!((d - 12.5).abs() < 1e-10);
    }

    #[test]
    fn test_squared_euclidean_symmetry() {
        let se = SquaredEuclidean::new();
        let p = vec![3.0, 1.0, 4.0];
        let q = vec![1.0, 5.0, 9.0];
        assert!(se.verify_symmetry(&p, &q));
    }

    #[test]
    fn test_squared_euclidean_zero() {
        let se = SquaredEuclidean::new();
        let p = vec![1.0, 2.0, 3.0];
        assert!((se.divergence(&p, &p)).abs() < 1e-10);
    }

    #[test]
    fn test_distance() {
        let se = SquaredEuclidean::new();
        let p = vec![0.0, 0.0];
        let q = vec![3.0, 4.0];
        // D = ½(9+16) = 12.5, distance = √25 = 5
        assert!((se.distance(&p, &q) - 5.0).abs() < 1e-10);
    }

    #[test]
    fn test_mahalanobis_identity() {
        let se = SquaredEuclidean::new();
        let maha = MahalanobisDistance::new(vec![vec![1.0, 0.0], vec![0.0, 1.0]]);
        let p = vec![1.0, 2.0];
        let q = vec![4.0, 6.0];
        assert!((se.divergence(&p, &q) - maha.divergence(&p, &q)).abs() < 1e-10);
    }

    #[test]
    fn test_mahalanobis_weighted() {
        let maha = MahalanobisDistance::new(vec![vec![2.0, 0.0], vec![0.0, 0.5]]);
        let p = vec![1.0, 0.0];
        let q = vec![0.0, 0.0];
        let d = maha.divergence(&p, &q);
        // A⁻¹ = diag(0.5, 2), diff = (1,0), result = ½ * 1*0.5*1 = 0.25
        assert!((d - 0.25).abs() < 1e-10);
    }
}
