//! Itakura-Saito divergence as a Bregman divergence.
//!
//! D_IS(p‖q) = p/q - ln(p/q) - 1 is the Bregman divergence generated by
//! φ(x) = -ln(x). Fundamental in spectral analysis and speech processing.

use serde::{Deserialize, Serialize};

/// Itakura-Saito divergence: D_IS(p‖q) = p/q - ln(p/q) - 1.
///
/// Generated by φ(x) = -ln(x), the IS divergence is the Bregman divergence
/// of choice for spectral density estimation and speech processing.
///
/// # Properties
///
/// - **Scale invariant**: D_IS(αp ‖ αq) = D_IS(p‖q) for α > 0
/// - **Non-negative**: D_IS ≥ 0 with equality iff p = q
/// - **Non-symmetric**: D_IS(p‖q) ≠ D_IS(q‖p) in general
/// - **Convex in p**: but not in q
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ItakuraSaito;

impl ItakuraSaito {
    /// Create a new Itakura-Saito divergence instance.
    pub fn new() -> Self {
        Self
    }

    /// Compute the IS divergence for scalar values.
    ///
    /// D_IS(p‖q) = p/q - ln(p/q) - 1
    pub fn divergence_scalar(&self, p: f64, q: f64) -> f64 {
        assert!(p > 0.0 && q > 0.0, "IS divergence requires positive inputs");
        p / q - (p / q).ln() - 1.0
    }

    /// Compute the IS divergence for vectors (sum over components).
    pub fn divergence(&self, p: &[f64], q: &[f64]) -> f64 {
        assert_eq!(p.len(), q.len());
        p.iter()
            .zip(q.iter())
            .map(|(&pi, &qi)| self.divergence_scalar(pi, qi))
            .sum()
    }

    /// Verify scale invariance: D_IS(αp ‖ αq) = D_IS(p‖q).
    pub fn verify_scale_invariance(&self, p: &[f64], q: &[f64], alpha: f64) -> bool {
        let scaled_p: Vec<f64> = p.iter().map(|x| alpha * x).collect();
        let scaled_q: Vec<f64> = q.iter().map(|x| alpha * x).collect();
        (self.divergence(&scaled_p, &scaled_q) - self.divergence(p, q)).abs() < 1e-10
    }

    /// Compute the IS divergence for spectral densities (per frequency bin).
    pub fn spectral_divergence(&self, spectrum_p: &[f64], spectrum_q: &[f64]) -> f64 {
        self.divergence(spectrum_p, spectrum_q) / spectrum_p.len() as f64
    }
}

impl Default for ItakuraSaito {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_is_zero_when_equal() {
        let is = ItakuraSaito::new();
        assert!((is.divergence_scalar(2.0, 2.0)).abs() < 1e-10);
    }

    #[test]
    fn test_is_positive() {
        let is = ItakuraSaito::new();
        assert!(is.divergence_scalar(3.0, 1.0) > 0.0);
        assert!(is.divergence_scalar(1.0, 3.0) > 0.0);
    }

    #[test]
    fn test_is_known_value() {
        let is = ItakuraSaito::new();
        // p/q = 2: D = 2 - ln(2) - 1 = 1 - ln(2) ≈ 0.3069
        let d = is.divergence_scalar(2.0, 1.0);
        assert!((d - (1.0 - 2.0_f64.ln())).abs() < 1e-10);
    }

    #[test]
    fn test_is_scale_invariance() {
        let is = ItakuraSaito::new();
        let p = vec![2.0, 3.0, 1.0];
        let q = vec![1.0, 2.0, 4.0];
        assert!(is.verify_scale_invariance(&p, &q, 5.0));
        assert!(is.verify_scale_invariance(&p, &q, 0.1));
    }

    #[test]
    fn test_is_nonsymmetric() {
        let is = ItakuraSaito::new();
        let d1 = is.divergence_scalar(2.0, 1.0);
        let d2 = is.divergence_scalar(1.0, 2.0);
        assert!((d1 - d2).abs() > 1e-6);
    }

    #[test]
    fn test_is_vector() {
        let is = ItakuraSaito::new();
        let p = vec![1.0, 1.0];
        let q = vec![1.0, 1.0];
        assert!((is.divergence(&p, &q)).abs() < 1e-10);
    }
}
