//! Kullback-Leibler divergence as a Bregman divergence.
//!
//! KL(p‖q) = Σ pᵢ ln(pᵢ/qᵢ) is the Bregman divergence with generating
//! function φ = Σ xᵢ ln(xᵢ) (negative entropy).

use serde::{Deserialize, Serialize};

/// Kullback-Leibler divergence: KL(p‖q) = Σ pᵢ ln(pᵢ/qᵢ).
///
/// This is the Bregman divergence generated by the negative entropy:
/// φ(x) = Σ xᵢ ln(xᵢ)
///
/// # Properties
///
/// - **Non-symmetric**: KL(p‖q) ≠ KL(q‖p) in general
/// - **Non-negative**: KL(p‖q) ≥ 0 (Gibbs' inequality), with equality iff p = q
/// - **Convex in p**: but not in q
/// - **Not a metric**: does not satisfy triangle inequality
///
/// # Interpretation
///
/// KL divergence measures the information lost when q is used to approximate p.
/// In information theory, it quantifies the inefficiency of assuming distribution q
/// when the true distribution is p.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KullbackLeibler;

impl KullbackLeibler {
    /// Create a new KL divergence instance.
    pub fn new() -> Self {
        Self
    }

    /// Compute KL(p‖q) = Σ pᵢ ln(pᵢ/qᵢ) for discrete distributions.
    ///
    /// # Panics
    ///
    /// Panics if p and q have different lengths or any qᵢ ≤ 0 where pᵢ > 0.
    pub fn divergence(&self, p: &[f64], q: &[f64]) -> f64 {
        assert_eq!(p.len(), q.len(), "p and q must have same dimension");
        p.iter()
            .zip(q.iter())
            .map(|(&pi, &qi)| {
                if pi <= 0.0 {
                    0.0
                } else if qi <= 0.0 {
                    f64::INFINITY
                } else {
                    pi * (pi / qi).ln()
                }
            })
            .sum()
    }

    /// Compute the symmetric JS divergence: ½ KL(p‖m) + ½ KL(q‖m) where m = ½(p+q).
    pub fn jensen_shannon(&self, p: &[f64], q: &[f64]) -> f64 {
        let m: Vec<f64> = p
            .iter()
            .zip(q.iter())
            .map(|(&pi, &qi)| 0.5 * (pi + qi))
            .collect();
        0.5 * self.divergence(p, &m) + 0.5 * self.divergence(q, &m)
    }

    /// Verify Gibbs' inequality: KL(p‖q) ≥ 0.
    pub fn verify_gibbs(&self, p: &[f64], q: &[f64]) -> bool {
        self.divergence(p, q) >= -1e-10
    }

    /// Compute the entropy H(p) = -Σ pᵢ ln(pᵢ).
    pub fn entropy(&self, p: &[f64]) -> f64 {
        -p.iter()
            .map(|&pi| if pi > 0.0 { pi * pi.ln() } else { 0.0 })
            .sum::<f64>()
    }

    /// Compute the cross-entropy H(p, q) = -Σ pᵢ ln(qᵢ).
    pub fn cross_entropy(&self, p: &[f64], q: &[f64]) -> f64 {
        -p.iter()
            .zip(q.iter())
            .map(|(&pi, &qi)| {
                if pi > 0.0 && qi > 0.0 {
                    pi * qi.ln()
                } else {
                    0.0
                }
            })
            .sum::<f64>()
    }

    /// Compute KL divergence for continuous distributions via numerical integration.
    ///
    /// Uses the trapezoidal rule over the provided samples.
    pub fn continuous(&self, p_samples: &[f64], q_samples: &[f64], dx: f64) -> f64 {
        assert_eq!(p_samples.len(), q_samples.len());
        let mut result = 0.0;
        for i in 0..p_samples.len() {
            if p_samples[i] > 0.0 && q_samples[i] > 0.0 {
                result += p_samples[i] * (p_samples[i] / q_samples[i]).ln();
            }
        }
        result * dx
    }
}

impl Default for KullbackLeibler {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_kl_identical_distributions() {
        let kl = KullbackLeibler::new();
        let p = vec![0.25, 0.25, 0.25, 0.25];
        assert!((kl.divergence(&p, &p)).abs() < 1e-10);
    }

    #[test]
    fn test_kl_nonnegativity() {
        let kl = KullbackLeibler::new();
        let p = vec![0.5, 0.5];
        let q = vec![0.3, 0.7];
        assert!(kl.verify_gibbs(&p, &q));
    }

    #[test]
    fn test_kl_nonsymmetric() {
        let kl = KullbackLeibler::new();
        let p = vec![0.5, 0.5];
        let q = vec![0.3, 0.7];
        let forward = kl.divergence(&p, &q);
        let backward = kl.divergence(&q, &p);
        assert!((forward - backward).abs() > 1e-6);
    }

    #[test]
    fn test_js_symmetric() {
        let kl = KullbackLeibler::new();
        let p = vec![0.5, 0.5];
        let q = vec![0.3, 0.7];
        let js_pq = kl.jensen_shannon(&p, &q);
        let js_qp = kl.jensen_shannon(&q, &p);
        assert!((js_pq - js_qp).abs() < 1e-10);
    }

    #[test]
    fn test_entropy_uniform() {
        let kl = KullbackLeibler::new();
        let p = vec![0.25, 0.25, 0.25, 0.25];
        let h = kl.entropy(&p);
        assert!((h - 4.0_f64.ln()).abs() < 1e-10);
    }

    #[test]
    fn test_kl_known_value() {
        let kl = KullbackLeibler::new();
        let p = vec![1.0, 0.0];
        let q = vec![0.5, 0.5];
        let d = kl.divergence(&p, &q);
        // KL = 1*ln(1/0.5) + 0 = ln(2)
        assert!((d - 2.0_f64.ln()).abs() < 1e-10);
    }
}
